//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.1
//     from Packages/cyggie.scene-changer/Runtime/Scripts/Input System/SceneChangerInputSystem.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Cyggie.SceneChanger.Runtime.InputSystems
{
    public partial class @SceneChangerInputSystem: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @SceneChangerInputSystem()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""SceneChangerInputSystem"",
    ""maps"": [
        {
            ""name"": ""SceneChanger"",
            ""id"": ""8f2f1571-e5b8-4c89-9ac6-c784ca750462"",
            ""actions"": [
                {
                    ""name"": ""Wait"",
                    ""type"": ""Button"",
                    ""id"": ""4e9aec44-c887-4565-b409-01160b2b294a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": []
        }
    ],
    ""controlSchemes"": []
}");
            // SceneChanger
            m_SceneChanger = asset.FindActionMap("SceneChanger", throwIfNotFound: true);
            m_SceneChanger_Wait = m_SceneChanger.FindAction("Wait", throwIfNotFound: true);
        }

        ~@SceneChangerInputSystem()
        {
            UnityEngine.Debug.Assert(!m_SceneChanger.enabled, "This will cause a leak and performance issues, SceneChangerInputSystem.SceneChanger.Disable() has not been called.");
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // SceneChanger
        private readonly InputActionMap m_SceneChanger;
        private List<ISceneChangerActions> m_SceneChangerActionsCallbackInterfaces = new List<ISceneChangerActions>();
        private readonly InputAction m_SceneChanger_Wait;
        public struct SceneChangerActions
        {
            private @SceneChangerInputSystem m_Wrapper;
            public SceneChangerActions(@SceneChangerInputSystem wrapper) { m_Wrapper = wrapper; }
            public InputAction @Wait => m_Wrapper.m_SceneChanger_Wait;
            public InputActionMap Get() { return m_Wrapper.m_SceneChanger; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(SceneChangerActions set) { return set.Get(); }
            public void AddCallbacks(ISceneChangerActions instance)
            {
                if (instance == null || m_Wrapper.m_SceneChangerActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_SceneChangerActionsCallbackInterfaces.Add(instance);
                @Wait.started += instance.OnWait;
                @Wait.performed += instance.OnWait;
                @Wait.canceled += instance.OnWait;
            }

            private void UnregisterCallbacks(ISceneChangerActions instance)
            {
                @Wait.started -= instance.OnWait;
                @Wait.performed -= instance.OnWait;
                @Wait.canceled -= instance.OnWait;
            }

            public void RemoveCallbacks(ISceneChangerActions instance)
            {
                if (m_Wrapper.m_SceneChangerActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ISceneChangerActions instance)
            {
                foreach (var item in m_Wrapper.m_SceneChangerActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_SceneChangerActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public SceneChangerActions @SceneChanger => new SceneChangerActions(this);
        public interface ISceneChangerActions
        {
            void OnWait(InputAction.CallbackContext context);
        }
    }
}
